name: example
description: Example app for the JsonDynamicWidget library

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.3.0
  automated_testing_framework_plugin_images: ^3.0.4
  desktop_window: ^0.4.0
  dotted_border: ^2.0.0+2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  json_dynamic_widget:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

# Required until XMl and Flutter SVG update to pull in 5.0.0
dependency_overrides:
  petitparser: ^4.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pages/
    - assets/secrets/
    - assets/widgets/
  fonts:
    - family: lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: metal
      fonts:
        - asset: assets/fonts/MetalMania-Regular.ttf
