name: example
description: Example app for the JsonDynamicWidget library

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.1.1
  automated_testing_framework_plugin_images: ^3.0.3
  desktop_window: ^0.4.0
  dotted_border: ^2.0.0+1
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  json_dynamic_widget:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pages/
    - assets/secrets/
    - assets/widgets/
  fonts:
    - family: lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: metal
      fonts:
        - asset: assets/fonts/MetalMania-Regular.ttf
