name: json_dynamic_widget
description: A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.
homepage: https://github.com/peiffer-innovations/json_dynamic_widget

version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  child_builder: ^2.0.0
  flutter:
    sdk: flutter
  form_validation: ^2.0.0
  json_class: ^2.0.0
  json_conditional: ^2.0.0+1
  json_schema2: ^2.0.0
  json_theme: ^2.0.0+1
  logging: ^1.0.0
  meta: ^1.3.0
  uuid: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   json_conditional:
#     path: ../json_conditional
#   json_theme:
#     path: ../json_theme

flutter:
  uses-material-design: true
