name: json_dynamic_widget
description: A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.
homepage: https://github.com/peiffer-innovations/json_dynamic_widget

version: 5.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  automated_testing_framework: ^4.0.0
  child_builder: ^2.0.0+3
  collection: ^1.16.0
  flutter:
    sdk: flutter
  form_validation: ^2.1.0+2
  interpolation: ^2.1.2
  json_class: ^2.1.2+4
  json_conditional: ^2.1.0+3
  json_schema2: ^2.0.2
  json_theme: ^4.0.0
  logging: ^1.0.2
  meta: ^1.7.0
  template_expressions: ^1.1.6
  uuid: ^3.0.6

false_secrets:
  - example/web/index.html

# dependency_overrides:
#   json_theme:
#     path: ../json_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
