name: json_dynamic_widget
description: A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.
publish_to: 'none' 

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  flutter:
    sdk: flutter
  child_builder: ^1.0.0+1
  form_validation: ^1.0.0+1
  json_class: ^1.0.3
  json_conditional: ^1.0.2
  json_theme: ^1.0.8
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  json_conditional:
    path: ../json_conditional
  json_theme:
    path: ../json_theme

flutter:
  uses-material-design: true
