name: 'json_dynamic_widget'
description: 'A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.'
homepage: 'https://github.com/peiffer-innovations/json_dynamic_widget'
version: '7.0.0-dev1'

environment:
  sdk: '>=3.0.0 <4.0.0'

analyzer:
  exclude:
    - 'lib/generated/**'

dependencies:
  child_builder: '^2.0.1'
  collection: '^1.16.0'
  execution_timer: '^1.0.2+4'
  flutter:
    sdk: 'flutter'
  form_validation: '^3.0.0'
  interpolation: '^2.1.2'
  json_class: '^3.0.0+1'
  json_conditional: '^3.0.0'
  json_dynamic_widget_annotations:
    path: ../json_dynamic_widget_annotations
  json_schema: '^5.1.2'
  json_theme: '^6.0.1'
  logging: '^1.2.0'
  meta: '^1.9.1'
  template_expressions: '^3.1.0'
  uuid: '^3.0.7'
  yaon: '^1.1.1'

dev_dependencies:
  flutter_lints: '^2.0.1'
  flutter_test:
    sdk: 'flutter'

dependency_overrides:
  json_dynamic_widget_annotations:
    path: ../json_dynamic_widget_annotations

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
