name: json_dynamic_widget
description: A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.
homepage: https://github.com/peiffer-innovations/json_dynamic_widget

version: 4.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  automated_testing_framework: ^3.2.2
  child_builder: ^2.0.0+2
  collection: ^1.15.0
  expressions: ^0.2.3
  flutter:
    sdk: flutter
  form_validation: ^2.1.0+1
  interpolation: ^2.1.2
  json_class: ^2.1.2+3
  json_conditional: ^2.1.0+2
  json_schema2: ^2.0.0+5
  json_theme: ^3.2.5
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.5

false_secrets:
  - example/web/index.html

# dependency_overrides:
#   json_theme:
#     path: ../json_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
