name: json_dynamic_widget
description: A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.
homepage: https://github.com/peiffer-innovations/json_dynamic_widget

version: 3.5.2

environment:
  sdk: ">=2.12.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  automated_testing_framework: ^3.1.1+2
  child_builder: ^2.0.0
  collection: ^1.15.0
  flutter:
    sdk: flutter
  form_validation: ^2.1.0
  interpolation: ^2.1.2
  json_class: ^2.1.2+1
  json_conditional: ^2.1.0
  json_path: ^0.3.0
  json_schema2: ^2.0.0+3
  json_theme: ^3.2.1
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.5

false_secrets:
  - example/web/index.html

# dependency_overrides:
#   json_theme:
#     path: ../json_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
