name: Flutter Pull Request Checker

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:stable

    steps:
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: flutter packages get
      - name: Dart Analyzer
        run: dartanalyzer lib
      - name: Code Format
        run: dartfmt --set-exit-if-changed -w lib test
      - name: Get dependencies
        run: flutter test
